# Generated by Django 4.2.7 on 2023-12-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_record_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=6),
        ),
    ]
